spring.application.name=backend 
server.port = 9000

# Configuration MySQL pour production
spring.datasource.url=jdbc:mysql://localhost:3306/eva_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}

# JPA pour MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initialisation des données
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# Logging
logging.level.root = ERROR
logging.level.com.openclassrooms = INFO
logging.level.org.springframework.boot.web.embedded.tomcat = INFO

# Désactiver le rapport d'autoconfiguration au démarrage
logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger=OFF
debug=false

# Configuration pour l'envoi de mails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SENDER_MAIL}
spring.mail.password=${SENDER_PWD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Export des fichiers
app.xls-data-model-dir=C:/Users/LCI/Documents/Developpement info/code_java/EVA/eva fichiers/modeles
app.xls-data-dir=C:/Users/LCI/Documents/Developpement info/code_java/EVA/eva fichiers/data
app.pdf-dir=C:/Users/LCI/Documents/Developpement info/code_java/EVA/eva fichiers/tests

# Upload de fichiers: augmente la limite pour /file/import
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Clé fixe JWT
jwt.secret.key=${JWT_SECRET_KEY}